repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0
    hooks:
    -   id: golangci-lint

-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
    -   id: go-test-repo-pkg

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
