name: Beerus CI Lint

on:
    push:
    pull_request:
        branches:
            - main

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
        GO_VERSION: '^1.23'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint PR Commits
        if: github.event_name == 'pull_request'
        uses: wagoid/commitlint-github-action@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}

      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
