name: Beerus Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install packages
        run: |
          cd .github/config
          ls
          npm install

      - name: Create Release Notes
        id: chglg
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: "true"
          git-user-name: "LucasMendesl"
          git-user-email: "mendes_lucas2006@hotmail.com"
          config-file-path: "./.github/config/changelog.js"
          skip-version-file: "true"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.chglg.outputs.tag }}
          name: ${{ steps.chglg.outputs.tag }}
          generate_release_notes: true
          body: ${{ steps.chglg.outputs.clean_changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
