name: CI Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.chglg.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install packages
        run: |
          cd .github/config
          ls
          npm install

      - name: Create Release Notes
        id: chglg
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: "true"
          git-user-name: "LucasMendesl"
          git-user-email: "mendes_lucas2006@hotmail.com"
          config-file-path: "./.github/config/changelog.js"
          skip-version-file: "true"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.chglg.outputs.tag }}
          name: ${{ steps.chglg.outputs.tag }}
          generate_release_notes: true
          body: ${{ steps.chglg.outputs.clean_changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            lucasmendesl/beerus
            ghcr.io/lucasmendesl/beerus
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=true
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lucasmendesl
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Short SHA
        id: sha
        run: echo "::set-output name=short::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            VERSION=${{ needs.release.outputs.tag }}
            COMMIT_SHA=${{ steps.sha.outputs.short }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
