name: Beerus Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create next version
        id: chglg
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit: "true"
          git-user-name: "LucasMendesl"
          git-user-email: "mendes_lucas2006@hotmail.com"
